CREATE TABLE STATION (
    ID INT PRIMARY KEY NOT NULL,
    NAME TEXT NOT NULL,
    ADDRESS TEXT NOT NULL,
    GPSX REAL NOT NULL,
    GPSY REAL NOT NULL,
    REFERENCE_VALUE REAL NOT NULL
);

CREATE TABLE READING (
    STATION INT NOT NULL,
    TIMESTAMP TEXT NOT NULL,
    DEPTH REAL NOT NULL
);

CREATE INDEX IDX_READING_STATION ON READING(STATION);

CREATE INDEX IDX_READING_TIMESTAMP ON READING(TIMESTAMP);