CREATE TABLE STATION (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT NOT NULL,
    ADDRESS TEXT NOT NULL,
    LAT REAL NOT NULL,
    LONG REAL NOT NULL,
    REFERENCE_VALUE REAL NOT NULL
);

CREATE TABLE READING (
    STATION INT NOT NULL,
    TIMESTAMP TEXT NOT NULL,
    DEPTH REAL NOT NULL
);

CREATE INDEX IDX_READING_STATION ON READING(STATION);

CREATE INDEX IDX_READING_TIMESTAMP ON READING(TIMESTAMP);


INSERT INTO
    STATION (NAME,ADDRESS,LAT,LONG,REFERENCE_VALUE)
    VALUES  ("Mjärdevi","localhost:12345",0.0,0.0,3.0);
    

INSERT INTO
    STATION (NAME,ADDRESS,LAT,LONG,REFERENCE_VALUE)
    VALUES  ("Gottfridsberg","localhost:12346",0.0,0.0,3.0);
    
